### ISSUE TITLE
Error loading emoji.json when running as Spring Boot

### ISSUE THREAD

**Issue by andporter** [felldo/JEmoji#3]
### JEmoji version

1.1.5

### Steps to reproduce

Thank you for making this library! I am using spring boot with maven

When I run the project directly using vscode everything works great, but when I run using the Spring Boot, this throws an exception trying to load the emojis.json file:

java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4980)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3754)
	at net.fellbaum.jemoji.EmojiManager.<clinit>(EmojiManager.java:37)

It seems like an issue with the class loader not looking at the correct path. I have used this code below in other projects, can you see if changing the `EmojiManager.readFileAsString` method using this will work for you and I think it should also work for Spring Boot

```
private static String readFileAsString() {
    ClassPathResource classPathResource = new ClassPathResource(PATH);
    try (InputStream inputStream = classPathResource.getInputStream(); InputStreamReader inputStreamReader = new InputStreamReader(inputStream); BufferedReader bufferedReader = new BufferedReader(inputStreamReader)) {
        return bufferedReader.lines().collect(Collectors.joining(System.lineSeparator()));
    } catch (Exception e) {
         throw new RuntimeException(e);
    }
}
```

### What is expected?

Able to load the emojis.json file while running as Spring Boot

### What is actually happening?

Getting an exception

java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4980)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3754)
	at net.fellbaum.jemoji.EmojiManager.<clinit>(EmojiManager.java:37)

**Comment by felldo** [comment]
Hi, thank you for reporting this issue.

Your suggestion is unfortunately spring specific so this cannot be used as a fix.
But I have already found a fix for this issue and a new version `1.1.6` is already being released, so it should be available anytime soon.
