### ISSUE TITLE
Emoji with variation selector treatment

### ISSUE THREAD

**Issue by gamer2810** [felldo/JEmoji#47]
### JEmoji version

1.3.3

### Steps to reproduce

Using libra emoji from Iphone 15 Pro (IOS 17.1.2) keyboard.
Invoke the following:
EmojiManager.replaceAllEmojis("♎️♎️", "")

### What is expected?

An empty string is returned

### What is actually happening?

A string with 2 invisible [characters](https://emojipedia.org/apple/ios-15.4/variation-selector-16) is returned.

**Comment by felldo** [comment]
Hi, thank you for reporting this missing feature. 

I've just released a new version `1.4.1` which adds support for Variation Selectors :)
