### ISSUE TITLE
Replace emoji with alias

### ISSUE THREAD

**Issue by BernhardAngerer** [felldo/JEmoji#48]
### What feature are you proposing?

Hi

Thanks for the very useful library!

It would be nice to have a new getter method in Emoji.java (getAlias()) that returns the first alias as String that was found. If nothing was found it could return ":unknown_emoji_alias:".

Now:
String aliasedEmojiText = EmojiManager.replaceAllEmojis(textWithEmojis, emoji -> emoji.getAllAliases().stream()
                              .findFirst()
                              .orElse(":unknown_emoji_alias:"));

Proposal:
String aliasedEmojiText = EmojiManager.replaceAllEmojis(textWithEmojis, Emoji::getAlias);

What do you mean?

**Comment by felldo** [comment]
Hi, thank you for the suggestion.

A new method that always returns an alias is not a viable option. Not every emoji might have an alias and then returning an alias that doesn't even exist is imo not useful (except maybe for your case). While I would agree that a method that returns just the first available alias might be a good convenient method but this wouldn't help you either in your case, as it would return an `Optional<String>`.
Though you could do `emoji.getFirstAlias().orElse("...")` which is shorter than what you currently have but you are still not able to use method references.

**Comment by BernhardAngerer** [comment]
In case of missing alias on an emoji, why not simply "aliasify" the emoji description to have at least a meaningful alias?

Example
Emoji:🙂‍↕️
Description: "Head Shaking Vertically"
Alias generated from Description: ":head_shaking_vertically:"

**Comment by felldo** [comment]
This is pretty useless. It doesn't make sense to do it like this, when not a single platform is interpreting this alias as an emoji. Usually the alias is only used for convenience as nobody wants to remember unicode characters. But if the alias doesn't result into the actual emoji, why bother even writing it? Therefore, I don't see why something like this should be in this library, when this seems more like a pretty specific usecase for you.

**Comment by BernhardAngerer** [comment]
I agree. It's really only helpful for my specific usecase. Thanks.
