### ISSUE TITLE
Why include getEmoji and getUnicode?

### ISSUE THREAD

**Issue by singpolyma** [felldo/JEmoji#50]
### Your Question

They seem to always return the same thing, yet not only are there two methods but two fields in memory for this?

**Comment by felldo** [comment]
Hi, thank you for reporting this issue. On the first look it seems that there was a mistake on the generation.
The generated JSON visually contains the correct and wanted value `"unicode" : "\uD83D\uDE00",` but nevertheless is still parsed as the normal unicode so it's equal to the emoji attribute.

**Comment by felldo** [comment]
Fixed in `v1.5.2`. The unicode attribute is now the string representation of the unicode value

**Comment by freya022** [comment]
> Fixed in `v1.5.2`. The unicode attribute is now the string representation of the unicode value

I'd consider updating the docs for both methods, so it's more clear which gives what.
`getUnicode()` makes it seem like it would return the raw emoji, something that can be pasted and displayed correctly, when it doesn't.
While `getEmoji()` effectively doesn't have any docs.
