### ISSUE TITLE
removeAllEmojis should also remove any U+FE0F present

### ISSUE THREAD

**Issue by singpolyma** [felldo/JEmoji#51]
### JEmoji version

1.4.1

### Steps to reproduce

EmojiManager.removeAllEmojis("🏂️\uFE0F") results in "\uFE0F"

### What is expected?

Should remove the emoji variant selector

### What is actually happening?

Leaves it in the string

**Comment by felldo** [comment]
Hi, I think this seems to be a mistake on your side. The snowboarder has a variant selector and that is also marked in the source code. But when copying your string and converting it to basic latin the following will be shown:
![image](https://github.com/felldo/JEmoji/assets/31566807/50fdfbf8-b5cb-4ea8-896e-2a0fe12f825f)
Therefore, one variant selector will be removed but not the additional one.
