### ISSUE TITLE
Move keywords and descriptions to separate modules

### ISSUE THREAD

**Issue by freya022** [felldo/JEmoji#55]
### What feature are you proposing?

Moving the localized keywords and descriptions to separate modules, reducing the main jar size to ~600 KB, which is quite more lightweight than 13.1 MB

You can also further reduce the size of those modules by switching to a format other than serialized objects, for example, Properties are a smaller, faster, easy alternative, and would also remove the [reachability data required by GraalVM's native image](https://www.graalvm.org/latest/reference-manual/native-image/metadata/#serialization)

**Comment by felldo** [comment]
I agree with moving the language files into an own module. It's really increases the library size by a lot and this feature is probably not used by users or if used they will probably use all languages for i18n reasons.

> You can also further reduce the size of those modules by switching to a format other than serialized objects, for example, Properties are a smaller, faster, easy alternative

I could not confirm this. When creating property files instead of the serialized objects it needed almost 2x the storage size. ~26,5MB for serialized objects and 46MB for property files and this only was for the description not counting the keywords

**Comment by freya022** [comment]
It just doesn't make sense to have properties be that large, each line is a key=value, while objects have some additional data attached to them.

However I dont think it's worthwhile anymore, due to the added complexity with having to split the keywords (some of them have commas in them, you'd have to escape them)

**Comment by freya022** [comment]
With the code below, you can see that, assuming we can read the escaped commas correctly, the size of all emoji keywords would go from 62.19 MB -> 48.28 MB uncompressed, or 7.83 -> 6.16 MB compressed.

```kotlin
fun main() {
    val descriptionPaths = ClassGraph()
        .acceptPackages("emoji_sources.keyword")
        .scan()
        .allResources
        .paths

    fun convert(entries: Map<String, List<String>>): ByteArray {
        val properties = Properties()
        for ((key, value) in entries) {
            // Assuming we know how to parse escaped commas
            properties.put(key, value.joinToString(",") { it.replace(",", "\\,") })
        }
        val writer = StringWriter()
        properties.store(writer, null)
        // Remove comments left by Properties#store
        return writer.toString().lines()
            .filterNot { it.startsWith("#") }
            .joinToString("\n")
            .encodeToByteArray()
    }

    var oldCompressedTotal = 0
    var oldTotal = 0
    var newCompressedTotal = 0
    var newTotal = 0
    descriptionPaths.forEach { path ->
        val oldData = EmojiManager::class.java.getResourceAsStream("/$path")!!.use(InputStream::readAllBytes)
        fun loadOld(): Map<String, List<String>> {
            return ByteArrayInputStream(oldData)
                .let(::ObjectInputStream)
                .use(ObjectInputStream::readObject) as Map<String, List<String>>
        }

        val newData = convert(loadOld())

        fun ByteArray.compress(): ByteArray {
            val baos = ByteArrayOutputStream()
            ZipOutputStream(baos, StandardCharsets.UTF_8).use {
                it.setLevel(9)
                it.putNextEntry(ZipEntry("test.properties"))
                it.write(this@compress)
                it.closeEntry()
            }
            return baos.toByteArray()
        }
        val oldCompressed = oldData.compress().size
        val newCompressed = newData.compress().size

        val sizeRatio = 100.0 / oldData.size * newData.size
        println("Converted '$path': ${oldData.size} B -> ${newData.size} B ($sizeRatio%)")

        oldTotal += oldData.size
        oldCompressedTotal += oldCompressed
        newTotal += newData.size
        newCompressedTotal += newCompressed
    }

    fun megabytes(bytes: Int): Double = bytes / 1024.0 / 1024.0
    println("Old total size: ${megabytes(oldTotal)} MB (${megabytes(oldCompressedTotal)} MB compressed)")
    println("New total size: ${megabytes(newTotal)} MB (${megabytes(newCompressedTotal)} MB compressed)")
}
```

**Comment by felldo** [comment]
> It just doesn't make sense to have properties be that large, each line is a key=value, while objects have some additional data attached to them.

It seems like you are already using compression. My approach was fairly simple

```kt
val filePath = "$fileOutputDir/src/main/resources/emoji_sources/descriptionprop/${dirName}"
File(filePath).apply {
    parentFile.mkdirs()
    if (!exists()) {
        createNewFile()
    }
}.let {
    val properties = Properties()
    descriptionMap.forEach { key, value ->
        value?.let { properties.put(key, it) }
    }
    FileOutputStream(it).use { fileOutStream ->
        properties.store(fileOutStream, null)
    }
}
```
which results in ~46MB solely for the descriptions.

Btw. a new version has been released today which splits the library into 2 modules. Now a `jemoji-languages` module exists which can be optionally added as a dependency to enable multi language support.

**Comment by freya022** [comment]
> It seems like you are already using compression

Unsure how I would be using compression, I read the deserialized map from the JEmoji JAR and write to a Properties instance, you can even run the code yourself without any change (preferrably in a separate project, to use the published JAR) and see the output
