### ISSUE TITLE
Emoji not being replaced

### ISSUE THREAD

**Issue by marcelcaferati** [felldo/JEmoji#7]
### JEmoji version

1.2.0

### Steps to reproduce

I am using the replace all method to replace with HTMLDecimal

like this:

EmojiManager.replaceAllEmojis(str, Emoji::getHtmlDecimalCode);

But apparently some emojis arent being replaced i get this error 

Incorrect string value: '\xF0\x9F\x8F\x8B\xE2\x80...' for column

This table isnt unicodemb4 so that value breaks the insert.

### What is expected?

The emojis to be replaced

### What is actually happening?

Not replacing the emojis

### Any additional comments?

That code appears to be a version of the weight lifting emoji, i dont think the clients are using random keyboard emojis on their phones.

It could be an oversight on the emoji variation, i tried all variations but i couldnt figure out exactly which one, i am now trying to log the full insert to figure out exactly what it is

Would it be viable to either fix this one emoji and make a method that removes just the non valid emojis?

The previous lib i used, wouldnt break the code like this on non supported emojis

**Comment by felldo** [comment]
Can you clarify what emoji exactly isn't replaced?
I have just released a new version `1.3.0` which should be available soon. Could you try with the new version if the issue still persists?

**Comment by marcelcaferati** [comment]
I wasnt able to find out the exact emoji that wasn't getting replaced.

I updated to 1.3.0 and kept the logs going, going to keep an eye on it and let you know!
